#Introduction to the Bioinformatics Armory#
#Create a code for reading nucleotides, counting them and realease A,C,G,T quantities#



def solve(a):
 A=0
 C=0
 G=0
 T=0
 for x in range(len(a)):
  if "A"==a[x]:
	A=A+1
  elif "C"==a[x]:
	C=C+1
  elif "G"==a[x]:
	G=G+1
  else:
	T=T+1
 return str(A)+" "+str(C)+" "+str(G)+" "+str(T)

x="TTTGTGTGCACTCTGTATCCGCATGTGTCCGCGACGTGCTAGTGCCTATCAGCGGGAACTGTATTCCATAACAGCACCAATTCGTCACGTTTCTCCGTTCGCCCTCAACTTATGTCTACACGTAAAAAGCACGCTGCGACCATAGGCATTGCCTGCCCTCATTTCAAGTAAGGACCCTACTTGCAAACACCATCCTCACTTCGCAGGAACCCGCTCGGGACGGACTACGCCCCCTTTTCTTCTTGAATCCCCTTGCTCTGCAGCACTGAGCGTCTCTAAATCTGTCGCACTGTTGATCGTGCCTTCGAATCTTAACTCCCACGGTTAAGTGCGAACCGCAACGGGACAGGGTCCGGCTAGACACCACCCTAGTTTAAGAACACATGGATCTAAGAGGAACAACCGTGGAGCTGTTATGGCATGCTTATATCGTGGCTAAAGGCGCTTTGTTGTTCTGGTATCTTCTGGATATGTGATCGCATTACTTCGACCGATGGATGAACGTCATGCATTAGTATTGGCAGTACAAGATCTCATTTTGGGCTGCAATCCCTCGGGTGGACGTACGCAAAGACAGCATTACACGGCACGCTGCGACTAAGACTAACAAAGGATCAATCAGCCGTCTATACTCCACTTAAACCTGTCCAGAGGCACGTGAGCAGCATTCGTGTAAATCTCCAATCAGGAGTCATATGAACGGGACGCGACAACGTTGAAGTGACTTAACATCGCCATAACTCGGTCGCATATGTCGGACGTGATATCTGTGAAGGTATTTCTCTCATGGAGAGCGTCGATACTCTCGGCTCCCGCCGTTTGACTGAGTTGCATTGATAAGATTCATCGGAATAGGCTGGATAGCGATGGTCCTGGACTGATTGGGCATAGGACATGCTGTAG"
print solve(x)
